
stages:
  - test
  - build
  - deploy

linux_build:
    stage: build
    image: ubuntu:14.04
    before_script:
      - apt-get update
      - apt-get install -y git cmake build-essential autoconf libtool pkg-config libssl-dev
      - git submodule update --init --recursive

    script:
      # curl
      - cd appupdaterlib/3d-party/curl
      - ./buildconf
      - ./configure
      - make
      - make install
      - cd ../../..
      
      # appUpdater
      - cd appupdaterlib
      - mkdir build
      - cd build
      - cmake ../
      - cd ..
      - cmake --build build --config Release
      - cd ..


      # updateExample
      - mkdir build
      - cd build
      - cmake ../
      - cd ..
      - cmake --build build --config Release