stages:
  - test
  - build
  - deploy

variables:
  APPUPDATERLIB_ARCHIVE: appupdaterlib.zip
  LINUX_LIB: https://drive.google.com/uc?export=download&id=1I-8FUazk26E7VOTHM07qUN4oktua2t1-
  WIN32_LIB: https://drive.google.com/uc?export=download&id=1XBgdECrvat73-ChVAOspjmAXDRicWM3S
  WIN64_LIB: https://drive.google.com/uc?export=download&id=1GW6vfpQmB9Ilhel-fcahGOSEsbugCqLX
  MACOS_LIB: https://drive.google.com/uc?export=download&id=1sq3AIUGtltKBZYXfsW-c9Y4VAhN5Xl2y

linux_build:
    stage: build
    image: ubuntu:14.04
    before_script:
      - apt-get update
      - apt-get install -y git unzip cmake build-essential autoconf libtool pkg-config libssl-dev wget chrpath
      - git submodule update --init --recursive
      - 'wget -L -O $APPUPDATERLIB_ARCHIVE "$LINUX_LIB"'
      - unzip $APPUPDATERLIB_ARCHIVE
      - mv ./appupdater ./3d-party
    script:
      # updateExample
      - mkdir build
      - cd build
      - cmake ../
      - cd ..
      - cmake --build build --config Release

      #prepare deploy
      - mkdir ./build/lib
      - cp ./3d-party/appupdater/lib/libappUpdaterShared.so ./build/lib
      - chrpath -r ./lib ./build/updateCUI
    artifacts:
      name: appupdater_example_linux
      paths:
          - ./build/updateCUI
          - ./build/lib/libappUpdaterShared.so
      expire_in: 1 day
    tags:
      - linux

win32_build:
    stage: build
    variables:
      BUILD_TOOL: 'Visual Studio 16 2019'
      PLATFORM: 'Win32'
    before_script:
      - './before_script_win.ps1 "$APPUPDATERLIB_ARCHIVE" "$WIN32_LIB"'
    script:
      - './script_win.ps1 "$QT_BIN_DIR" "$BUILD_TOOL" "x86" "$PLATFORM"'
    artifacts:
      name: appupdater_example_win
      paths:
        - ./build/Release/*
        - ./qml_example/release/*
      expire_in: 1 day
    tags:
      - win

win64_build:
    stage: build
    variables:
      BUILD_TOOL: 'Visual Studio 16 2019'
      PLATFORM: 'x64'
    before_script:
      - './before_script_win.ps1 "$APPUPDATERLIB_ARCHIVE" "$WIN64_LIB"'
    script:
      - './script_win.ps1 "$QT_BIN_DIR" "$BUILD_TOOL" "x64"'
    artifacts:
      name: appupdater_example_win
      paths:
        - ./build/Release/*
        - ./qml_example/release/*
      expire_in: 1 day
    tags:
      - win


macos_build:
    stage: build
    before_script:
      - git submodule update --init --recursive
      - 'curl -L -o $APPUPDATERLIB_ARCHIVE "$MACOS_LIB"'
      - unzip $APPUPDATERLIB_ARCHIVE
      - mv ./appupdater ./3d-party
    script:
      # updateExample
      - mkdir build
      - cd build
      - cmake ../
      - cd ..
      - cmake --build build --config Release

      #prepare deploy
      - cp -R ./3d-party/appupdater/lib/ ./build/Release
    artifacts:
      name: appupdater_example_mac
      paths:
          - ./build/updateCUI
          - ./build/Release/*
      expire_in: 1 day
    tags:
      - macos